### ISSUE TITLE
Request for graphs in plotly

### ISSUE THREAD

**Issue by manojjenago** [chranga/renkocharts#5]
Hi ,

I am enjoying this code.
I have a request for plotting the graphs in Plotly (import plotly.graph_objects as go).
I have few peice of code that runs in Plotly, I want to integrate this renko chart to the existing strategy. 
Is there anyway we can draw this renko chart using Plotly. That will be a great help ...Please guide.

Thanks,
Manoj

**Comment by chranga** [comment]
@manojjenago  Turns out, it was a lot easier than I expected. [Here](https://github.com/chranga/renkocharts/blob/main/convert_to_renko_ohlc-plotly_v1.ipynb) is the same code but using Plotly rendering.

**Comment by manojjenago** [comment]
> @manojjenago Turns out, it was a lot easier than I expected. [Here](https://github.com/chranga/renkocharts/blob/main/convert_to_renko_ohlc-plotly_v1.ipynb) is the same code but using Plotly rendering.

Perfect.
Thank you so much...
Thanks,
Manoj
